[project]
name = "grr-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pyinstaller>=6.16.0",
    "pyside6>=6.10.0",
    "scipy>=1.16.2",
]
